---
title: "Pull Run Statistics"
author: "Genomics Center at Clalit"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: true
    toc_float: false
---

```{r initial_setup}
bs_analysis_folder<-'/media/SSD/Bioinformatics/Projects/basespace_automation_202206/'

```

```{r setup, include=FALSE,warning=F,message=F}

project_dir<-hpo_analysis_folder
knitr::opts_knit$set(root.dir=project_dir)
knitr::opts_chunk$set(echo = F)
library(ProjectTemplate)
setwd(project_dir)
load.project()

main_output_folder<-glue('./output/basespace_results_{Sys.Date()}')
if (!dir.exists(main_output_folder)){dir.create(main_output_folder)}

```

```{r run_attributes}
workgroup <-'Sequencing Center - Collaborative'
verify_workgroup(workgroup)
workgroup_name<-tolower(stringr::str_replace_all(workgroup,'[\\s\\-]+','_'))

all_runs<-get_all_runs()
message(glue('There are {nrow(all_runs)} runs in the workgroup'))

all_runs_stats<-NULL
for (run_id in all_runs%>%pull(Id)){
  message(glue('Retrieving stats for {run_id}'))
  run_stats<-get_run_statistics(run_id)
  all_runs_stats<-all_runs_stats%>%bind_rows(run_stats)
}

# save run stats
write.table(all_runs_stats,sep='\t',file=glue('./data/run_stats/{workgroup_name}_runstats_{Sys.Date()}.csv'),
            row.names = F,
            quote = F)
```

```{r analyze_runs}
stat_output_name<-'20221028'

run_stat_files<-c('./data/run_stats/genoox_collaborative_runstats_2022-10-28.csv',
                  './data/run_stats/sequencing_center_runstats_2022-10-28.csv',
                  './data/run_stats/bgu_collaborative_runstats_2022-10-28.csv',
                  './data/run_stats/sequencing_center_collaborative_runstats_2022-10-28.csv')

all_run_stats<-NULL
for (rfile in run_stat_files){
  run_stats<-readr::read_delim(rfile,delim='\t')
  all_run_stats<-all_run_stats%>%bind_rows(run_stats)
}

write.table(all_run_stats,sep='\t',file=glue('./output/runstats_{Sys.Date()}.csv'),
            row.names = F,
            quote = F)

plot_data<-all_run_stats%>%select(ExperimentName,contains('SequencingStats'),-contains(c('Num','Href','IsIndexed','Chemistry','Cycle')))


```
