---
title: "Run DRAGEN Popgen"
author: "Genomics Center at Clalit"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    toc: true
    toc_float: false
---

```{r initial_setup}
bs_analysis_folder<-'/media/SSD/Bioinformatics/Projects/basespace_automation_202206/'

```

```{r setup, include=FALSE,warning=F,message=F}

project_dir<-hpo_analysis_folder
knitr::opts_knit$set(root.dir=project_dir)
knitr::opts_chunk$set(echo = F)
library(ProjectTemplate)
setwd(project_dir)
load.project()

main_output_folder<-glue('./output/basespace_results_{Sys.Date()}')
if (!dir.exists(main_output_folder)){dir.create(main_output_folder)}

```

```{r run_attributes}
# Set project name
app_name<-'DRAGEN PopGen'
app_version<-'3.10.5'

workgroup <-'Genoox - collaborative'
verify_workgroup(workgroup)
run_sheet_name_prefix<-'bgu_wes_idt_run_023'
app_session_name<-run_sheet_name_prefix
ht_ref<-'hg38'
pipeline_mode<-'projects'
project_name<-run_sheet_name_prefix
project_name<-stringr::str_replace(project_name,'\\s+','_')

project_id<-get_project_id_by_name(project_name,create_project_if_not_available = F)

# Option 1: Collect projects from biosamples
# source_projects<-get_project_ids_from_biosamples_sheet('./data/biosamples_sheets/bgu_collaborative_2022-10-27.csv')
# source_projects<-paste0(source_projects,collapse=',')

# Option 2: Choose a project with all the samples
source_projects<-'20061048'

# all_datasets<-get_all_datasets()
# project_datasets<-all_datasets%>%filter(Project.Name==project_name)%>%pull(Name)

generate_dragen_popgen_runsheet(
  run_sheet_name_prefix = run_sheet_name_prefix,
  app_session_name = app_session_name,
  project_id = project_id,
  source_projects = source_projects,
  ht_ref = ht_ref,
  pipeline_mode = pipeline_mode,
  output_file_prefix = glue('{project_name}.dragen_popgen')
)

run_attributes<-parse_run_sheet(glue('./data/run_sheets/{run_sheet_name_prefix}.dragen_popgen.csv'),attributes_list=list())
# now verify every bs has a fastq file
launch_application(app_name = app_name,
                   app_version = app_version,
                   run_attributes = run_attributes,
                   command_line_args = '-o "arbitrary:--gg-remove-nonref true"')
### !!!! Please note, sometimes it takes alot of time for the run to start and the BS disconnects. it doesnt mean  the run wont go.. need to check whether it is still in the queued status !!!


```

